# name: E2E Tests

# on:
# push:
#   branches: [ "master" ]
# pull_request:
# workflow_dispatch:

# jobs:
# e2e-tests:
#   timeout-minutes: 30
#   runs-on: ubuntu-latest

#   strategy:
#     matrix:
#       node-version: [16.x, 18.x, 20.x]

#   steps:
#   - uses: actions/checkout@v3
#   - name: Use Node.js ${{ matrix.node-version }}
#     uses: actions/setup-node@v3
#     with:
#       node-version: ${{ matrix.node-version }}
#       cache: 'npm'
#   - name: Run End-To-End Tests
#     run: ./scripts/e2e-test.sh
#   - name: Publish Test Results
#     if: always()
#     uses: actions/upload-artifact@v3
#     with:
#       name: test-results
#       path: |
#         e2e/cypress/screenshots
#         e2e/cypress/videos
